### PR TITLE
ENH Linux implementation

### PR DESCRIPTION
**Pull request by caspervdw**
This implements the nd2 reader in linux.

@stevendbrown I think I covered your timestamp bug. On Linux, the ND2SDK returns the Unix timestamp although the documentation states that it is the JDN timestamp (which is the case on windows systems)

Could you confirm if this works?

### CODE REVIEW

**Comment by caspervdw** [comment]
@tacaswell  Could you turn Travis on for this repo?

**Comment by caspervdw** [comment]
@stevendbrown I actually didn't test the timestamp, now I did and it came out to be 0.0 (as you described). This is an issue with the ND2SDK, which I cannot solve. Merging this.

**Comment by stevendbrown** [comment]
@caspervdw I've been told by LIM that the current SDK on the ND2SDK website has the 0.0 bug fixed albeit without a version number change. I have not yet tested this on my own systems to verify.

**Comment by caspervdw** [comment]
@stevendbrown Please keep me updated about the testing results. I checked out the current `.so` file against the one on their website and I didn't see any difference in the binary files.

**Pull request merged**
