### PR TITLE
ENH OSX implementation

### PR DESCRIPTION
**Pull request by caspervdw**
Based on the work of @stevendbrown in #12 

Could you test if I got it right? And for clarity, is it required to add the nd2sdk framework folder to the PATH variable? If so, it should be documented in the readme.

### CODE REVIEW

**Comment by stevendbrown** [comment]
Hi @caspervdw, sorry for the lag in getting this done. When I pull `osx-implement` in a new branch based on the current `master` and try to `import pims_nd2`, I get segmentation fault and the kernel dies. It seems to crash during [`from pims.frame import Frame`](https://github.com/soft-matter/pims_nd2/blob/master/pims_nd2/nd2reader.py#L5).

**Comment by stevendbrown** [comment]
Your changes work for me once I fix my somewhat hack-job packages setup. ;-) Is there a line you could point me to regarding your second question about PATH?

**Comment by caspervdw** [comment]
Thanks for checking. I just wonder if you appended your environment variable "PATH" manually on your system.

**Comment by stevendbrown** [comment]
Ah, I see. No, I did not.

**Comment by caspervdw** [comment]
Merged. Thanks again for your work on this!

**Comment by stevendbrown** [comment]
My pleasure! Thanks for writing the harness & helping me learn how to contribute.

In the name of tying up loose ends, I tried dropping `'Versions', '1'` from the `LoadLibrary` call for OS X and it still fails on my system (with an OSError of `file too short`), and adding the explicit paths back results successful loading.

**Pull request merged**
